name: Deploy to Amazon ECS
on:
  push


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.3

      - name: Gradle build
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 6.9.1
          arguments: build -PTOKEN=${{ secrets.TOKEN }}

      - name: Configure AWS keys/creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker build & push to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: faceitapihelper
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg TOKEN_ARG=${{ secrets.TOKEN }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: faceitapihelper-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: faceitapihelper
          cluster: arn:aws:ecs:us-east-2:908484539917:cluster/faceitapihelper
          wait-for-service-stability: true
